/* 全部内容为虚构:人物、作品、奖项均不对应任何真实对象。 */
window.ACTOR = {
  name: "林知远",
  nameEn: "Lin Zhiyuan",
  lede: "他最擅长演话少的人:修表匠、气象员、夜班急诊医生。",
  facts: [
    ["出生", "1989 年 3 月,青岛"],
    ["身高", "183 cm"],
    ["出道", "2012 年,《初雪》"],
    ["作品", "12 部(电影 7、剧集 4、综艺 1)"],
  ],
  bio: [
    "林知远 1989 年生于青岛,大学读的是大气科学,毕业后在海洋观测站工作了两年。2012 年,一部校友短片邀他客串,他从此改了行;同年他在《初雪》里演了个配角,台词不到十句。",
    "此后十多年,他很少接商业大片,时间多留给低成本的现实题材。为了《无声的邻居》里的修表匠,他学了三个月手语;《北纬三十度》让他拿到海岸线电影节最佳男主角。",
    "他说自己选角色只看一点:台词少,需要观察的东西多。",
  ],
  awards: [
    ["海岸线电影节 最佳男主角", "《北纬三十度》", "2023"],
    ["云端视听奖 年度剧集男演员", "《灯下》", "2025"],
    ["北岸电影周 最佳男配角", "《旧港》", "2020"],
    ["海岸线电影节 最佳男主角提名", "《无声的邻居》", "2022"],
    ["青年影人奖 最佳新人", "《初雪》", "2013"],
  ],
  costars: [
    { name: "沈清禾", note: "同演 3 部", hair: "long", bg: ["#7f8d92", "#4c5a5e"] },
    { name: "顾言", note: "同演 2 部", hair: "short", bg: ["#8f8a82", "#5a554e"] },
    { name: "苏念", note: "同演 2 部", hair: "long", bg: ["#6f8487", "#3f5558"] },
    { name: "郑海", note: "同演 2 部", hair: "short", bg: ["#97908a", "#625b55"] },
    { name: "乔远", note: "同演 1 部", hair: "short", bg: ["#7d8a8e", "#485458"] },
  ],
  /* signature:代表作(会被红圈圈住);look:画面生成参数 */
  works: [
    { id: "huichao", title: "回潮", year: 2025, type: "电影", role: "许望(渔村修船工)", director: "沈清禾", rating: 8.1,
      line: "退潮后的渔村里,一艘船修了三十年,还没下水。",
      look: { scene: "sea", a: "#9fb0b8", b: "#d8d2c4", c: "#f4ead0", g: "#2f4a52", fx: 0.62, boat: true } },
    { id: "dengxia", title: "灯下", year: 2024, type: "剧集", extra: "共 12 集", role: "周敬(急诊科夜班医生)", director: "顾言", rating: 7.9, signature: true,
      line: "一个夜班,十二位病人,和一间永远亮着灯的值班室。",
      look: { scene: "window", a: "#0e2b2c", b: "#1b4a49", c: "#f3b25a", g: "#07100f", fx: 0.34 } },
    { id: "beiwei", title: "北纬三十度", year: 2023, type: "电影", role: "陆衡(气象站观测员)", director: "沈清禾", rating: 8.6, signature: true,
      line: "台风前夜,山顶气象站只剩他一个人,和一台不肯停的风速计。",
      look: { scene: "field", a: "#c9d6dc", b: "#eef0ea", c: "#ffffff", g: "#7d8f6e", fx: 0.28, station: true } },
    { id: "manche", title: "慢车", year: 2023, type: "综艺", extra: "常驻嘉宾", role: "本人", director: "方可", rating: 7.2,
      line: "六个人坐绿皮车横穿一个省,不许看手机。",
      look: { scene: "room", a: "#f0c9a8", b: "#f7e6c8", c: "#fff7e0", g: "#8a5a48", fx: 0.5 } },
    { id: "yanyuhuo", title: "盐与火", year: 2022, type: "剧集", extra: "共 8 集", role: "沈既白(后厨主理人)", director: "顾言", rating: 8.0,
      line: "一间快要倒闭的海鲜馆,最后一个冬天的后厨。",
      look: { scene: "room", a: "#3a2a22", b: "#8a4a2e", c: "#ffcf8a", g: "#1c120d", fx: 0.68, steam: true } },
    { id: "wusheng", title: "无声的邻居", year: 2021, type: "电影", role: "老何(修表匠)", director: "苏念", rating: 8.3, signature: true,
      line: "他听不见,却是整条巷子里最先知道谁家出事的人。",
      look: { scene: "closeup", a: "#14110e", b: "#2b2218", c: "#ffd9a0", g: "#0c0a08", fx: 0.36 } },
    { id: "chunfen", title: "春分", year: 2020, type: "剧集", extra: "共 10 集", role: "乔远(中学物理教师)", director: "方可", rating: 8.4,
      line: "一间教室,一个学期,一道没有人做出来的题。",
      look: { scene: "window", a: "#cfd8d4", b: "#e9eeea", c: "#ffffff", g: "#6a7873", fx: 0.36, day: true } },
    { id: "jiugang", title: "旧港", year: 2019, type: "电影", role: "郑海(码头调度员)", director: "沈清禾", rating: 7.8, signature: true,
      line: "港口要搬迁了,他每天照旧给没有船的泊位排班。",
      look: { scene: "sea", a: "#3b3a52", b: "#d98a5a", c: "#ffd29a", g: "#1d2230", fx: 0.4, fig: true } },
    { id: "yebangongjiao", title: "夜班公交", year: 2018, type: "剧集", extra: "共 6 集", role: "宋杰(末班车司机)", director: "苏念", rating: 7.5,
      line: "末班车上,每一站都有人上来,也有人不下。",
      look: { scene: "street", a: "#0d1424", b: "#233a5e", c: "#ffd36b", c2: "#5ad1c8", g: "#05070d", fx: 0.7 } },
    { id: "qiyue", title: "七月的信", year: 2017, type: "电影", role: "老邮递员", director: "苏念", rating: 7.7,
      line: "最后一个夏天,他把积压了二十年的信一封封送了出去。",
      look: { scene: "field", a: "#a9d3d8", b: "#f3f0d8", c: "#ffffff", g: "#5c8a52", fx: 0.58 } },
    { id: "shujia", title: "暑假", year: 2015, type: "电影", role: "林叔(民宿老板)", director: "方可", rating: 7.4,
      line: "海边小镇的暑假,一家民宿接待了所有不想回家的人。",
      look: { scene: "sea", a: "#6fb4d6", b: "#e8f1ea", c: "#ffffff", g: "#2e7b9a", fx: 0.5, boat: true } },
    { id: "chuxue", title: "初雪", year: 2012, type: "电影", role: "同学(配角)", director: "顾言", rating: 7.0,
      line: "校园短片改编的长片,他的第一个镜头是背影。",
      look: { scene: "field", a: "#aeb7c2", b: "#e6e9ee", c: "#ffffff", g: "#d7dce3", fx: 0.42, fig: true } },
  ],
};
